### PR TITLE
Added option to display candidates from avy-goto-line-above (and below) in reverse order

### PR DESCRIPTION
**Pull request by walseb**
One of my main problems with using avy for vertical movements is that using avy-goto-line would bring up all the easiest to type keys at the top, avy-goto-line-below solved this by having the easiest to type characters closest to the cursor, but avy-goto-line-above can't do this, and instead displays the easiest to reach keys at the top. The result is vertical movements taking more keypresses, and making it harder for muscle memory to build up (since you now have to memorize two sets of keys, one for going up and one for going down). To fix this I added a parameter to allow the user to choose if they want their keys going from bottom to top (should reversing keys like this be default behaviour for avy-goto-line-above?). I also thought having a key for going one line down was a waste of keys, so i added the option of defining your own scope when calling avy-goto-line-above and below (should the scope described also be default behaviour?).

I also fixed up the comments of avy-goto-subword-0 a bit (didn't notice the order was wrong in my last pull request)

Also, i'm not sure if line 1434 was the best way to do it (i wanted nreverse to be run on candidates if bottom-up was non-nil)

### CODE REVIEW

**Comment by walseb** [comment]
Just to visualise, this is what avy avy-goto-line-above looks like out of the box right now

And this is what it would look like if reversing key order was default behaviour

**Comment by walseb** [comment]
@abo-abo In case you forgot and have time, this PR is still open

**Comment by abo-abo** [comment]
Hi, thanks for the reminder. I like the PR. But I need an Emacs Copyright Assignment for changes over 15 lines. Do you have one? See README for more info.

**Comment by walseb** [comment]
I just sent a request for one, I will remind you again when all the paperwork is done

**Comment by walseb** [comment]
@abo-abo The paperwork is done! What should I do now? Paste the signed PDF here?

**Comment by abo-abo** [comment]
@walseb Thanks, I think I see you on the `copyright.list` file. But the email address is different, and there's no name on your Github account. So it's difficult to make the connection (not just for me, but for other people and automated tools).

Could you please squash the PR into a single commit using email `s.wal...@gmail.com`? Or ask the copyright clerk to also add the current email on your commit to the `copyright.list` file?

**Comment by walseb** [comment]
Sorry, I didn't pay much attention when creating the account. Everything is fixed now.

**Comment by walseb** [comment]
@abo-abo Sorry, I didn't pay much attention when creating the account. Everything is fixed now.

**Comment by abo-abo** [comment]
Merged, thanks.

**Pull request closed without merging**
