### PR TITLE
Add new avy-style to use words as sequences

### LINKED ISSUE #176: Use words instead of key sequences
For me, jumping by typing words (e.g. `the` or `of`) is much faster than reading typing arbitrary sequences of characters (e.g. `lk`) even if key characters are shorter. It'd be nice if there was a setting for that. (If you decide to add it, I can provide a list of words.)

### PR DESCRIPTION
**Pull request by fabacino**
This PR adds a new `avy-style` named `words` which uses actual words instead of arbitrary key sequences. 

The words can be customized through `avy-words`. They do not have to be in English but should obey the rule stated in the description i.e. each word must contain at least one "vowel" used in the English language. This makes it easy to add random key sequences in case the number of words provided does not suffice for all the jump targets. It is possible to make these vowels customizable as well but I figured it would probably be overkill.

Fixes #176

### CODE REVIEW

**Comment by abo-abo** [comment]
Great job! Thanks.

**Comment by alphapapa** [comment]
Wow, this is really cool!

The only thing that could make it better is if you could easily filter the list of words to, e.g. letters on the home row.  Although, since QWERTY only has one vowel on the home row, maybe that wouldn't be terribly practical.  :)

**Comment by fabacino** [comment]
The words are used in the exact order specified in `avy-words`. Currently they are listed in alphabetical order which is probably not the best way as similar looking words are often next to each other (e.g. gum, gun, gut) and words which are easy to type are not preferred over hard ones. Feel free too arrange them in an order which optimises one or both of these points.

**Comment by viniciussbs** [comment]
@fabacino It's possible to use style `'words` only for specific functions?

**Comment by fabacino** [comment]
@viniciussbs Should be possible by using `avy-styles-alist`.

**Pull request merged**
