### PR TITLE
Add kill and save region/lines functionality.

### PR DESCRIPTION
**Pull request by magicdirac**
I do not know how to update my previous pull request, so I open a new request here.

Add six functions.
Three for kill region or lines to kill-ring using avy.
`avy-kill-region`
`avy-kill-whole-line`
`avy-kill-region-or-whole-line`
and the other three for save them to kill-ring.
`avy-kill-ring-save-region`
`avy-kill-ring-save-whole-line`
`avy-kill-ring-save-region-or-whole-line`

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. What's the email address that you used for your CA? The one you're using now is `magicdirac@users.noreply.github.com`, and it's not in the Emacs CA file.

Could you run e.g. this in your Avy repository and re-commit?

```
git config user.email "foo@bar.com"
```

The above command will make git use this email for all subsequent commits to the current repository.

**Comment by magicdirac** [comment]
I just updated the info and pushed to master branch. 
I do not know how can I update this pull request,
Should I open a new pull request?

**Comment by abo-abo** [comment]
> magicdirac@gmail.com

I don't see this email on the `gnuorg/copyright.list` file. Could you please email the FSF clerk and ask him to update that file?

Once it's there, I can do everything else, there's no need for another PR.

**Comment by magicdirac** [comment]
@abo-abo Get confirmed from FSF. 
You can go ahead and pull from the master branch. 

BTW could you remove email from last post. thanks.

**Comment by abo-abo** [comment]
> avy-kill-region-or-whole-line

Thanks. I added everything except these sort of commands. I don't think they belong in avy.el.

**Pull request closed without merging**
