### PR TITLE
Search only in the visible region

### LINKED ISSUE #108: avy--regex-candidates takes long time on a window with many hidden lines
avy on a huge org buffer takes 10 or more second on a Intel Core i5 system.  This is because the buffer has too many lines hidden and avy searches through.

### PR DESCRIPTION
**Pull request by yashi**
The current version of `avy--regex-candidates` first searches for the
given regex then skip the match if it's invisible.  This works fine with
less than a few thousand lines of buffer, however, it takes quit time if
your have tens of thousand lines hidden, say, in org file.

This patch reverse the strategy. Find all visible regions in given the
window first, then map the original search function to that list.  This
change reduced candidates search time from 10 or more seconds to instant
on my 100,000+ lines of org file.

It might be possible to have hundreds of visibility-interleaved regions
in a huge window on the 4K or 8K monitor in near the future, but this
reversed strategy should be fast enough for those system.

This fixes #108.

### CODE REVIEW

**Comment by yashi** [comment]
Forgot to mention that `avi--find-visible` and its friends are taken from org.el.  Hope licensing issue is ok.

**Comment by abo-abo** [comment]
Thanks for the patch. It looks OK, I'll test it more later.

> Hope licensing issue is ok.

Since the change is >15 lines, you need the Emacs Copyright Assignment in order for me to merge, since this package is on GNU ELPA.  Do you have it? It's a good thing to have, also works for contributions to Org mode, GELPA packages and core Emacs.

**Comment by yashi** [comment]
Yes, I have signed the Emacs Copyright Assignment.  Also, Some of my
changes are in org-mode.

**Comment by abo-abo** [comment]
Thanks a lot for the code. I've merged it with minor changes (renames, docstrings, and `cons`/`dolist` in some places).  Let me know if it still works fine.

**Comment by yashi** [comment]
It works fine here.  Thank you for merging it and for your fix, I'll learn
from your changes.  ;-)

**Pull request closed without merging**
