### PR TITLE
avy.el (avy--read-candidates): Update

### PR DESCRIPTION
**Pull request by ketanaka**
Handle BS(Back Space) for deletes the last char entered.

### CODE REVIEW

**Comment by abo-abo** [comment]
So you want <kbd>C-h</kbd> to delete? Is that a vi thing or something?

**Comment by ketanaka** [comment]
**Yes**, I want `C-h` to delete, that's all.

My settings are as follows.

```elisp
(global-set-key (kbd "C-h") 'delete-backward-char)
(global-set-key (kbd "C-M-;") 'avy-goto-char-timer)
(setq avy-timeout-seconds nil)
```

**Comment by abo-abo** [comment]
Thanks.

**Comment by ketanaka** [comment]
@abo-abo Thank you so much!

**Pull request closed without merging**
