### PR TITLE
Add license file with GPLv3

### PR DESCRIPTION
**Pull request by skangas**
This adds a license file, as required in the GPL.

Thanks!

### CODE REVIEW

**Comment by abo-abo** [comment]
Is this really required by Emacs packages?

We already have this:
```elisp
;; For a full copy of the GNU General Public License
;; see <http://www.gnu.org/licenses/>.
```

I think that should be enough.

**Comment by skangas** [comment]
I'm not in a good position to answer that currently. Further discussion on emacs-devel has also left me wondering if this is really necessary. I am waiting to see the result of that discussion: https://lists.gnu.org/archive/html/emacs-devel/2022-01/msg00048.html

**Comment by abo-abo** [comment]
Thanks. Keep me posted. I would prefer to not include extra stuff in the repo since it pollutes the `grep` results sometimes.

**Comment by skangas** [comment]
It seems like there are no further followups to this, so I suppose we can leave it alone. Sorry for the noise, and thanks!

**Pull request closed without merging**
