### PR TITLE
Add new command `avy-move-region'

### PR DESCRIPTION
**Pull request by YorkZ**
Hi Oleh,

I just added a new functionality to move a region.

York

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks a lot. However, you've contributed before, and there's a 15 line cumulative limit, unless you have an Emacs Copyright Assignment.  It's just simple paperwork that you need to contribute to Emacs, org-mode, or any packages in GNU ELPA, like avy. See [more info](https://github.com/abo-abo/avy#copyright-assignment).

But if you already have the papers signed, I can just merge, since the command looks fine.

**Comment by srid** [comment]
@YorkZ appreciate your attention here as I'm in need of this function.

**Comment by wbolster** [comment]
Any chance we can move this issue forward? Any chance @YorkZ can do something about this? Or perhaps @abo-abo can reimplement this in a slightly different way.

(tbh, i think this is just legalese nonsense. it's just slightly tweaked copy/pasted logic anyway...)

**Comment by abo-abo** [comment]
@wbolster I very little time these days to rewrite the functionality myself.  But I have no problem mering good a PR from someone with an Emacs CA.

If you want this to be merged faster, rewrite it yourself, get an assignment and open a new PR.

**Comment by YorkZ** [comment]
I will probably sign the paper and send it out this weekend.

**Comment by abo-abo** [comment]
@YorkZ thanks for the effort. I understand that it's a bit of a hassle. But being in GNU ELPA means that avy can reach many more users.

Additionally, since you request the CA for Emacs, you can send patches not only to avy, but also anything in GNU ELPA, Org mode, and the Emacs core.

**Comment by YorkZ** [comment]
Update: As promised, I've finally signed the assignment paper, and have sent it over to FSF on Mar 26, 2016. A few days after sending out the paper, I sent an email to Donald R. Robertson at FSF to follow up, but I still haven't got any reply yet.

I will update here as soon as I got any response.


Thank you,
York

**Comment by YorkZ** [comment]
Finally, I've received the paper signed by FSF. Turns out that FSF had some technical issue preventing me from receiving emails from them. So I guess you can merge my contribution now.

**Comment by abo-abo** [comment]
@YorkZ Thanks a lot! Welcome on board!

**Pull request closed without merging**
